version: "3.8"

services:
  # Kafka Broker (using KRaft mode, no separate Zookeeper needed for single node)
  kafka:
    image: bitnami/kafka:latest # Consider a specific version like 'bitnami/kafka:3.7.0' for stability
    container_name: kafka
    ports:
      - "9092:9092" # Kafka broker listener for clients
      - "9093:9093" # Internal controller listener
    environment:
      KAFKA_CFG_PROCESS_ROLES: "broker,controller"
      KAFKA_CFG_NODE_ID: "1"
      KAFKA_CFG_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093"
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9092"
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT"
      ALLOW_PLAINTEXT_LISTENER: "yes"
    volumes:
      - kafka_data:/bitnami/kafka
    networks:
      - smart_parking_net

  # Apache Cassandra Database - ENSURE THESE MEMORY SETTINGS ARE PRESENT
  cassandra:
    image: cassandra:4.1
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=smart-parking-cluster
    networks:
      - smart_parking_net

  spark-master:
    image: bitnami/spark:3.5.0
    container_name: spark-master
    hostname: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_MASTER_PORT=7077
      - SPARK_MASTER_WEBUI_PORT=8080
      - SPARK_MASTER_HOST=0.0.0.0 # Ensures it binds to all interfaces for host access
    ports:
      - "7077:7077" # Expose client port to host
      - "8081:8080" # Expose Web UI port to host
    networks:
      - smart_parking_net

  spark-worker:
    image: bitnami/spark:latest
    container_name: spark-worker
    depends_on:
      - spark-master
    environment:
      SPARK_MODE: worker
      SPARK_MASTER_URL: spark://spark-master:7077
      SPARK_WORKER_CORES: 1
      SPARK_WORKER_MEMORY: 1G
    volumes:
      - spark_worker_data:/bitnami/spark
    networks:
      - smart_parking_net

volumes:
  kafka_data:
  cassandra_data:
  spark_master_data:
  spark_worker_data:

networks:
  smart_parking_net: